#node1.toml
[server]
port = 5558
[node]
detect-drivers = false

[relay]
# Default Appium server endpoint
url = "http://localhost:4728"
status-endpoint = "/status"
# Stereotypes supported by the service. The initial number is "max-sessions", and will allocate 
# that many test slots to that particular configuration
configs = [
    "3", "{\"platformName\": \"Android\", \"appium:platformVersion\": \"12\", \"appium:deviceName\": \"Infinix X665\", \"appium:automationName\": \"UiAutomator2\"}"
]